config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  # topページ
  root 'users#show'
  # ↑編集予定
  get 'home/index'
  get 'home/about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # sessions registration メール転送に利用　使用の場合、cnfig/environments/development.rbのusername: paswword入力

  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get 'follows'
      get 'followers'
    end
  end

  # フォロー機能
  post 'follow/:id' => 'relationships#create', as: "follow"
  # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: "unfollow"
  # フォローを外す

  # 検索機能
  get '/search' => 'search#search'

  resources :books, only: [:show, :index, :edit, :create, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resource :book_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  # チャット機能 chat content:text,room name:string,user_roomモデル作成:  chats roomsコントローラー作成 尚,チャットの投票は非同期

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController


	def search
		@model = params["search"]["model"]
		@content = params["search"]["content"]
		@how = params["search"]["how"]
		@datas = search_for(@model, @content, @how)
	end

	  private
    def search_for(model, content, how)
      if model == 'user'
        if how == 'perfect'
          User.where(name: content)
        elsif how == 'forward'
          User.where('name LIKE ?', content+'%')
          # 前方一致
          # name Like ?  nameカラムを検索
          # where 与えられた条件を全て消す
        elsif how == 'backward'
          User.where('name LIKE ?', '%'+content)
          # 後方一致
        else
          User.where('name LIKE ?', '%'+content+'%')
          # 部分一致
        end
      elsif model == 'book'
        if how == 'perfect'
          Book.where(title: content)
        elsif how == 'forward'
          Book.where('title LIKE ?', content+'%')
        elsif how == 'backward'
          Book.where('title LIKE ?', '%'+content)
        else
          Book.where('title LIKE ?', '%'+content+'%')
        end
      end
    end

	# private
	# def match(model, content)
	# 	if model == 'user'
	# 		User.where(name: content)
	# 	elsif model == 'book'
	# 		Book.where(title: content)
	# 	end
	# end

	# def forward(model, content)
	# 	if model == 'user'
	# 		User.where("name LIKE ?", "#{content}%")
	# 	elsif model == 'book'
	# 		Book.where("title LIKE ?", "#{content}%")
	# 	end
 #    end

 #    def backward(model, content)
 #    	if model == 'user'
 #    		User.where("name LIKE ?", "%#{content}")
 #        elsif model == 'book'
 #        	Book.where("title LIKE ?", "%#{content}")
 #        end
 #    end

 #    def partical(model, content)
 #    	if model == 'user'
 #    		User.where("name LIKE ?", "%#{content}%")
 #    	elsif model == 'book'
 #    		Book.where("title LIKE ?", "%#{content}%")
 #    	end
 #    end

 #    def search_for(how, model, content)
 #    	case how
 #    	when 'match'
 #    		match(model, content)
 #    	when 'forward'
 #    		forward(model, content)
 #    	when 'backward'
 #    		backward(model, content)
 #    	when 'partical'
 #    		partical(model, content)
 #    	end
 #    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="container">

  <div class="row">

    <div class="col-xs-10">


     <% if @model == "user" %>

        <!-- Users検索一覧 -->
        <h2>Users</h2>

        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
           <% @datas.each do |users| %>

            <tr>
              <td>
                <%= attachment_image_tag users, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
              </td>
              <td>
                <%= users.name %>
              </td>
              <td>
                フォロー数 : <%= users.follower.count %>
              </td>
              <td>
                フォロワー数 : <%= users.followed.count %>
              </td>
              <td>
              <!-- フォローボタン -->
              <% unless users == current_user %>
                  <% if current_user.following?(users) %>
                   <%= link_to "フォロー外す", unfollow_path(users.id), method: :delete %>
                    <% else %>
                   <%= link_to "フォローする", follow_path(users.id), method: :post %>
                  <% end %>
              <% end %>
              <!-- フォローボタンここまで -->
              </td>
              <td>
                <%= link_to "Show",user_path(users.id) %>
              </td>
            </tr>
           <% end %>
          </tbody>
        </table>

     <% else %>
          <!-- Books検索結果一覧 -->
          <h2>Books</h2>

          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="4"></th>
              </tr>
            </thead>

            <tbody>
              <% @datas.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <!-- いいね機能ここまで -->

                <td id="favorites_buttons_<%= book.id %>">
                <%= render partial: 'favorites/favorites', locals: { book_detail: book} %>
                </td>

                <!-- いいね機能ここまで -->
                <td class="comment-count">コメント数 :<%= book.book_comments.count %>
                </td>
              </tr>
             <% end %>
            </tbody>
           </table>
     <% end %>
    </div>
  </div>
</div>