config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  # topページ
  root 'users#show'
  # ↑編集予定
  get 'home/index'
  get 'home/about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # sessions registration メール転送に利用　使用の場合、cnfig/environments/development.rbのusername: paswword入力

  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get 'follows'
      get 'followers'
    end
  end

  # フォロー機能
  post 'follow/:id' => 'relationships#create', as: "follow"
  # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: "unfollow"
  # フォローを外す

  # 検索機能
  get '/search' => 'search#search'

  resources :books, only: [:show, :index, :edit, :create, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resource :book_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  # チャット機能 chat content:text,room name:string,user_roomモデル作成:  chats roomsコントローラー作成 尚,チャットの投票は非同期

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	# Bookモデルに対して、Userモデルとの関係
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end

	validates :title, presence: true
	# 本のタイトルが空欄以外
	validates :body, presence: true, length: {maximum: 200}
	# 感想200文字以内

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @book =Book.new
    @books = Book.all
    @user = current_user
  end

  def show
  	@book_detail = Book.find(params[:id])
  	@book = Book.new
  	@books = Book.all
    @user = @book_detail.user
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	# current_user サインインしているユーザー
  	if @book.save
  	flash[:notice2] = "Book was successfully created."
  	redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user = current_user
    render action: :index
   end
  end

  def update
  	book = Book.find(params[:id])
  	if book.update(book_params)
  	 flash[:notice] = "Book was successfully updated."
  	 redirect_to book_path(book.id)
  	else
  	 flash[:notice] = "error"
  	 @book = Book.find(params[:id])
     render action: :edit
    end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
   end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	flash[:notice] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  # index リソースの一覧表示
  # new リソースを新規作成
  # create リソースを新規作成して追加
  # edit リソースを更新するためのフォーム
  # show レコードの内容を表示する
  # update リソースを更新する
  # destroy リソースを削除する

  private

  def book_params
     params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
            <!-- プロフィール -->
            <!-- user: @user -->
             <h2>User info</h2>
             <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
             <table class="table">
              <tbody>
                <tr>
    	            <th>name</th>
    	            <th><%= user.name %></th>
                </tr>
                <tr>
    	            <th>introduction</th>
    	            <th><%= user.introduction %></th>
                </tr>
                <tr>
                  <th>follows</th>
                  <th>
                    <%= link_to follows_user_path(user.id) do %>
                    <%= user.follower.count %>
                    <% end %>
                    </th>
                </tr>
                <tr>
                  <th>followes</th>
                  <th>
                    <%= link_to followers_user_path(user.id) do %>
                    <%= user.followed.count %>
                    <% end %>
                  </th>
                </tr>
              </tbody>
             </table>
             <div class="row">
               <% if user == current_user %>
                 <%= link_to  edit_user_path(@user.id) do %>
                  <span class= "col-xs-12 btn btn-default glyphicon glyphicon-wrench"></span>
                 <% end %>
               <% end %>

               <!-- フォローボタン -->
               <% unless user == current_user %>
                  <% if current_user.following?(user) %>
                   <%= link_to "フォロー外す", unfollow_path(user.id), class: "btn btn-primary col-xs-8", method: :delete %>
                    <% else %>
                   <%= link_to "フォローする", follow_path(user.id), class: "btn btn-success col-xs-8", method: :post %>
                  <% end %>
               <% end %>
               <!-- フォローボタンここまで -->
             </div>

app/views/books/_list2.html.erb
             <!-- 新規投票欄↓ -->
             <!-- book: @book  @book= Book.new -->
             <h2>New book</h2>
               <%= form_for(book) do |book| %>
                 <div class="field row">
                   <label for="book_title">Title</label>
                   <%= book.text_field :title, class: "col-xs-12" %>
                 </div>

                 <div class="field row">
                   <label for="book_opinion">Opinion</label>
                   <%= book.text_area :body, class: "col-xs-12" %>
                 </div>

                 <div class="actions row">
                   <%= book.submit "Create Book", class: "btn btn-primary col-xs-12" %>
                 </div>
               <% end %>

app/views/books/edit.html.erb
<div class="container">


  <p class="error_explanation"><%= flash[:notice] %></p>


  <div class="row">
	  <div class="col-md-6 col-md-offset-3">
		 <h1>Editing Book</h1>

     <%= form_for(@book) do |f| %>

       <div class="field row">
         <label for="book_title">Title</label>
         <%= f.text_field :title ,class: "col-xs-12 book_title" %>
       </div>

       <div class="field row">
         <label for="book_opinion">Opinion</label>
         <%= f.text_area :body ,class: "col-xs-12 book_body" %>
       </div>

       <div class="actions row">
         <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
       </div>
     <% end %>
       <!-- リンク先↓ -->
       <%= link_to 'Show',book_path %> |
       <%= link_to 'Back',books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <p id="notice"></p>

  <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <div class="error-box">
       <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li>error</li>
          <li><%= message %></li>
        <% end %>
       </ul>
      </div>
    </div>
  <% end %>

  <div class="row">

    <div class="col-xs-3">
    <%= render 'books/list', user: @user %>
    <%= render 'books/list2', book: @book %>
    <!-- 共通部分テンプレート -->
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="4"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            	<%= link_to user_path(book.user) do %>
            	<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
            	<% end %>
            </td>
            <td>
                <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
                <%= book.body %>
            </td>
            <!-- いいね -->

            <td id="favorites_buttons_<%= book.id %>">
            <%= render partial: 'favorites/favorites', locals: { book_detail: book} %>
            </td>

            <!-- kokomade -->
              <td class="comment-count">コメント数 :<%= book.book_comments.count %>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-3">
    <%= render 'books/list', user: @user %>
    <%= render 'books/list2', book: @book %>
    <!-- 共通部分テンプレート -->
    </div>

    <p class="successfully"><%= flash[:notice] %></p>
    <p class="successfully"><%= flash[:notice2] %></p>


    <div class="col-xs-9">
      <h2>Book detail</h2>
      <!-- book.idの詳細画面 -->

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book_detail.user) do %>
                <%= attachment_image_tag @book_detail.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %><br>
                <%= @book_detail.user.name %>
                <!-- ＠book_detail (id)のuserの名前 -->
              <% end %>
            </td>
            <td>
              <%= @book_detail.title %>
            </td>
            <td>
              <%= @book_detail.body %>
            </td>

            <!-- いいね機能 -->

            <td id="favorites_buttons_<%= @book_detail.id %>">
            <%= render partial: 'favorites/favorites', locals: { book_detail: @book_detail} %>
            </td>

            <!-- いいね機能ここまで -->
            <!-- コメント件数 -->
            <td class="comment-count">コメント数 :<%= @book_detail.book_comments.count %>
            </td>
            <!-- ここまで -->
           <% if current_user.id == @book_detail.user_id %>
            <td>
              <%= link_to "Edit", edit_book_path(@book_detail.id), class: "btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy",book_path(@book_detail.id), class: "btn-sm btn-danger", method: :delete,"data-confirm" => "Are you sure?" %>
            </td>
           <% else %>
            <td></td>
            <td></td>
           <% end %>
          </tr>
        </tbody>
      </table>

      <!-- コメント一覧 -->

      <div id="comments_area">
        <%= render partial: 'book_comments/comment', locals: {book: @book_detail.book_comments} %>
      </div>

      <!-- コメント一覧ここまで -->

      <!-- <form class="mt-20"> -->
      <div class="comment-form">

      <%= render partial: 'book_comments/comment_form', locals: { book_detail: @book_detail, book_comment: @book_comment} %>

      </div>
      <!-- </form> -->
    </div>
  </div>
</div>