config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  # topページ
  root 'users#show'
  # ↑編集予定
  get 'home/index'
  get 'home/about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # sessions registration メール転送に利用　使用の場合、cnfig/environments/development.rbのusername: paswword入力

  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get 'follows'
      get 'followers'
    end
  end

  # フォロー機能
  post 'follow/:id' => 'relationships#create', as: "follow"
  # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: "unfollow"
  # フォローを外す

  # 検索機能
  get '/search' => 'search#search'

  resources :books, only: [:show, :index, :edit, :create, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resource :book_comments, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :rooms, only: [:create, :show]
  # チャット機能 chat content:text,room name:string,user_roomモデル作成:  chats roomsコントローラー作成 尚,チャットの投票は非同期

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	# Bookモデルに対して、Userモデルとの関係
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end

	validates :title, presence: true
	# 本のタイトルが空欄以外
	validates :body, presence: true, length: {maximum: 200}
	# 感想200文字以内

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :chats, dependent: :destroy
	has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # :database_authenticatable（パスワードの正確性を検証）
  # :registerable（ユーザ登録や編集、削除）
  # :recoverable（パスワードをリセット）
  # :rememberable（ログイン情報を保存）
  # :validatable（emailのフォーマットなどのバリデーション）

  validates :name, presence: true, length: 2..20
  # user名前２から20文字いない
  validates :introduction, length: {maximum: 50}
  # プロフィール文50文字いない
  attachment :profile_image

  # Userモデルに対して、1:Nになるよう関連
  # class_name  一つのモデルに対して、二つのアソシエーション経路を組む場合に多用する
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  # validationする前にaddress_1を行う
  before_validation :address_1
  def address_1
    "%s %s %s"%([self.prefecture_code, self.address_city, self.address_street])
  end
  geocoded_by :address_1
  after_validation :geocode

  has_many :following_user, through: :follower, source: :followed
  # 自分がフォローすている人
  has_many :follower_user, through: :followed, source: :follower
  # 自分をフォローしている人
  # source  class_nameとほぼ同じ
  # through 中間テーブルが複数ある場合に利用。throughオプションで中間テーブルを指定すれば、経路を決めることができる
  # 下記変更アクション名 follow,unfollow = create,destroy
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # ユーザーをフォローする
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # ユーザーのフォローを外す
  def following?(user)
    following_user.include?(user)
  end
  # フォローしていればtrueを返す


  # 下記によって、prefectureメソッドが生成され、 都道府県コード、都道府県名が参照できるようになります。
  include JpPrefecture
  jp_prefecture :prefecture_code

  # postal_codeからprefecture_nameに変換するメソッドを用意します．
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @book =Book.new
    @books = Book.all
    @user = current_user
  end

  def show
  	@book_detail = Book.find(params[:id])
  	@book = Book.new
  	@books = Book.all
    @user = @book_detail.user
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	# current_user サインインしているユーザー
  	if @book.save
  	flash[:notice2] = "Book was successfully created."
  	redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user = current_user
    render action: :index
   end
  end

  def update
  	book = Book.find(params[:id])
  	if book.update(book_params)
  	 flash[:notice] = "Book was successfully updated."
  	 redirect_to book_path(book.id)
  	else
  	 flash[:notice] = "error"
  	 @book = Book.find(params[:id])
     render action: :edit
    end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
   end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	flash[:notice] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  # index リソースの一覧表示
  # new リソースを新規作成
  # create リソースを新規作成して追加
  # edit リソースを更新するためのフォーム
  # show レコードの内容を表示する
  # update リソースを更新する
  # destroy リソースを削除する

  private

  def book_params
     params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	before_action :authenticate_user!, :only => [:create]

	def create
		if UserRoom.where(:user_id => current_user.id, :room_id => params[:chat][:room_id]).present?
			@chat = Chat.create(params.require(:chat).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
		else
			redirect_back(fallback_location: root_path)
		end
	end

 # <%= form_for @chat do |f| %>
 #      <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
 #      <%= f.hidden_field :room_id, :value => @room.id %>
 #      <br>
 #      <%= f.submit "投稿する", class: "btn btn-primary" %>
 #    <% end %>
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <div class="header-box">
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span class="title-text">Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home" %>
            </li>
            <li>
              <%= link_to ' Users', users_path, class: "glyphicon glyphicon-user" %>
            </li>
            <li>
              <%= link_to ' Books', books_path, class: "glyphicon glyphicon-book" %>
            </li>
            <li>
              <%= link_to ' logout', destroy_user_session_path, :method => :delete, class: "glyphicon glyphicon-log-out"  %>
            </li>
          <% else %>
            <li>
              <%= link_to ' Home', root_path, class: "glyphicon glyphicon-home" %>
            </li>
            <li>
              <%= link_to ' About', home_about_path, class: "glyphicon glyphicon-link" %>
            </li>
            <li>
              <%= link_to ' sign up', new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
            </li>
            <li>
              <%= link_to ' login', new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</div>
  <% if user_signed_in? %>
    <div class="search-form">
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'search[content]' %>
        <%= select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= select_tag 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"}) %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
  <% end %>

  <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
 </body>
</html>